---

- name: ASSERT | Check vars
  assert:
    that:
      - 'redis_maxmemory_policy is none or redis_maxmemory_policy in redis_maxmemory_policy_available'
      - 'redis_maxmemory_samples is none or redis_maxmemory_policy in redis_maxmemory_samples_policies'

- name: APT | Install redis
  apt: >
    pkg=redis-server
    state=present
    update_cache=yes
    cache_valid_time=3600
    default_release={{ redis_apt_target }}

- name: TEMPLATE | Deploy Redis config file
  template: >
    src=etc/redis/redis.conf.j2
    dest=/etc/redis/redis.conf
  notify: restart redis

- name: LINEINFILE | Manage ulimit
  lineinfile: >
    line='{% if redis_ulimit is none %}# ULIMIT=65536{% else %}ULIMIT={{ redis_ulimit }}{% endif %}'
    regexp='^(#\s)?ULIMIT'
    dest=/etc/default/redis-server
  notify: restart redis
